name: Calming Renewal
favicon: null
layout_spectrum: 0.11251410143449903
typography_spectrum: 0.1406655025202781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5326179219409823
  lightness: 0.18872666894458234
  saturation: 0.5025188222061843
  rhythmicContrast: 0.5009480121079832
purpose: []
